name: Cypress Tests
on: push
jobs:
  cypres-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/register.cy.js,cypress/e2e/transfer.cy.js
